/**
 * F1 Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CarResponse { 
    id?: string;
    model?: string | null;
    chassisNumber?: string | null;
    engineManufacturer?: string | null;
    driverName?: string | null;
}

