/**
 * F1 Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CarResponse } from './carResponse';


export interface CarResponsePagedList { 
    items?: Array<CarResponse> | null;
    page?: number;
    pageSize?: number;
    totalCount?: number;
    readonly hasNextPage?: boolean;
    readonly hasPreviousPage?: boolean;
}

