/**
 * F1 Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChampionshipResponse { 
    id?: string;
    name?: string | null;
    year?: number;
    teamsCount?: number;
    winnerId?: string | null;
    winnerName?: string | null;
}

