/**
 * F1 Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DriverType } from './driverType';


export interface CreateDriverRequest { 
    firstName: string;
    lastName: string;
    nationality: string;
    dateOfBirth: string;
    driverType: DriverType;
    teamId: string;
}
export namespace CreateDriverRequest {
}


