/**
 * F1 Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateCarRequest { 
    model: string;
    chassisNumber: string;
    engineManufacturer: string;
    driverId?: string | null;
}

