/**
 * F1 Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const DriverType = {
    Main: 'Main',
    Reserve: 'Reserve'
} as const;
export type DriverType = typeof DriverType[keyof typeof DriverType];

