/**
 * F1 Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DriverType } from './driverType';


export interface DriverResponse { 
    id?: string;
    firstName?: string | null;
    lastName?: string | null;
    nationality?: string | null;
    dateOfBirth?: string;
    driverType?: DriverType;
    teamId?: string;
    teamName?: string | null;
    hasCar?: boolean;
}
export namespace DriverResponse {
}


