/**
 * F1 Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TeamResponse { 
    id?: string;
    name?: string | null;
    country?: string | null;
    championshipName?: string | null;
    driversCount?: number;
}

